// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyImpulseArgs {
    pub impulse_x: f64,
    pub impulse_y: f64,
}

impl From<ApplyImpulseArgs> for super::Reducer {
    fn from(args: ApplyImpulseArgs) -> Self {
        Self::ApplyImpulse {
            impulse_x: args.impulse_x,
            impulse_y: args.impulse_y,
        }
    }
}

impl __sdk::InModule for ApplyImpulseArgs {
    type Module = super::RemoteModule;
}

pub struct ApplyImpulseCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_impulse`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_impulse {
    /// Request that the remote module invoke the reducer `apply_impulse` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_apply_impulse`] callbacks.
    fn apply_impulse(&self, impulse_x: f64, impulse_y: f64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `apply_impulse`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ApplyImpulseCallbackId`] can be passed to [`Self::remove_on_apply_impulse`]
    /// to cancel the callback.
    fn on_apply_impulse(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f64, &f64) + Send + 'static,
    ) -> ApplyImpulseCallbackId;
    /// Cancel a callback previously registered by [`Self::on_apply_impulse`],
    /// causing it not to run in the future.
    fn remove_on_apply_impulse(&self, callback: ApplyImpulseCallbackId);
}

impl apply_impulse for super::RemoteReducers {
    fn apply_impulse(&self, impulse_x: f64, impulse_y: f64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "apply_impulse",
            ApplyImpulseArgs {
                impulse_x,
                impulse_y,
            },
        )
    }
    fn on_apply_impulse(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f64, &f64) + Send + 'static,
    ) -> ApplyImpulseCallbackId {
        ApplyImpulseCallbackId(self.imp.on_reducer(
            "apply_impulse",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::ApplyImpulse {
                                    impulse_x,
                                    impulse_y,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, impulse_x, impulse_y)
            }),
        ))
    }
    fn remove_on_apply_impulse(&self, callback: ApplyImpulseCallbackId) {
        self.imp.remove_on_reducer("apply_impulse", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `apply_impulse`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_apply_impulse {
    /// Set the call-reducer flags for the reducer `apply_impulse` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn apply_impulse(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_apply_impulse for super::SetReducerFlags {
    fn apply_impulse(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("apply_impulse", flags);
    }
}
