// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::respawn_balls_schedule_type::RespawnBallsSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `respawn_balls_schedule`.
///
/// Obtain a handle from the [`RespawnBallsScheduleTableAccess::respawn_balls_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.respawn_balls_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.respawn_balls_schedule().on_insert(...)`.
pub struct RespawnBallsScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<RespawnBallsSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `respawn_balls_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RespawnBallsScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RespawnBallsScheduleTableHandle`], which mediates access to the table `respawn_balls_schedule`.
    fn respawn_balls_schedule(&self) -> RespawnBallsScheduleTableHandle<'_>;
}

impl RespawnBallsScheduleTableAccess for super::RemoteTables {
    fn respawn_balls_schedule(&self) -> RespawnBallsScheduleTableHandle<'_> {
        RespawnBallsScheduleTableHandle {
            imp: self
                .imp
                .get_table::<RespawnBallsSchedule>("respawn_balls_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RespawnBallsScheduleInsertCallbackId(__sdk::CallbackId);
pub struct RespawnBallsScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RespawnBallsScheduleTableHandle<'ctx> {
    type Row = RespawnBallsSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RespawnBallsSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RespawnBallsScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RespawnBallsScheduleInsertCallbackId {
        RespawnBallsScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RespawnBallsScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RespawnBallsScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RespawnBallsScheduleDeleteCallbackId {
        RespawnBallsScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RespawnBallsScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RespawnBallsSchedule>("respawn_balls_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct RespawnBallsScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RespawnBallsScheduleTableHandle<'ctx> {
    type UpdateCallbackId = RespawnBallsScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RespawnBallsScheduleUpdateCallbackId {
        RespawnBallsScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RespawnBallsScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RespawnBallsSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RespawnBallsSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `respawn_balls_schedule`,
/// which allows point queries on the field of the same name
/// via the [`RespawnBallsScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.respawn_balls_schedule().scheduled_id().find(...)`.
pub struct RespawnBallsScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RespawnBallsSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RespawnBallsScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `respawn_balls_schedule`.
    pub fn scheduled_id(&self) -> RespawnBallsScheduleScheduledIdUnique<'ctx> {
        RespawnBallsScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RespawnBallsScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RespawnBallsSchedule> {
        self.imp.find(col_val)
    }
}
