// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::update_balls_schedule_type::UpdateBallsSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `update_balls_schedule`.
///
/// Obtain a handle from the [`UpdateBallsScheduleTableAccess::update_balls_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.update_balls_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.update_balls_schedule().on_insert(...)`.
pub struct UpdateBallsScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<UpdateBallsSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `update_balls_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UpdateBallsScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UpdateBallsScheduleTableHandle`], which mediates access to the table `update_balls_schedule`.
    fn update_balls_schedule(&self) -> UpdateBallsScheduleTableHandle<'_>;
}

impl UpdateBallsScheduleTableAccess for super::RemoteTables {
    fn update_balls_schedule(&self) -> UpdateBallsScheduleTableHandle<'_> {
        UpdateBallsScheduleTableHandle {
            imp: self
                .imp
                .get_table::<UpdateBallsSchedule>("update_balls_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UpdateBallsScheduleInsertCallbackId(__sdk::CallbackId);
pub struct UpdateBallsScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UpdateBallsScheduleTableHandle<'ctx> {
    type Row = UpdateBallsSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UpdateBallsSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UpdateBallsScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UpdateBallsScheduleInsertCallbackId {
        UpdateBallsScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UpdateBallsScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UpdateBallsScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UpdateBallsScheduleDeleteCallbackId {
        UpdateBallsScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UpdateBallsScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UpdateBallsSchedule>("update_balls_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct UpdateBallsScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UpdateBallsScheduleTableHandle<'ctx> {
    type UpdateCallbackId = UpdateBallsScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UpdateBallsScheduleUpdateCallbackId {
        UpdateBallsScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UpdateBallsScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UpdateBallsSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UpdateBallsSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `update_balls_schedule`,
/// which allows point queries on the field of the same name
/// via the [`UpdateBallsScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.update_balls_schedule().scheduled_id().find(...)`.
pub struct UpdateBallsScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UpdateBallsSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UpdateBallsScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `update_balls_schedule`.
    pub fn scheduled_id(&self) -> UpdateBallsScheduleScheduledIdUnique<'ctx> {
        UpdateBallsScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UpdateBallsScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UpdateBallsSchedule> {
        self.imp.find(col_val)
    }
}
