// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::update_balls_schedule_type::UpdateBallsSchedule;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateBallsArgs {
    pub schedule: UpdateBallsSchedule,
}

impl From<UpdateBallsArgs> for super::Reducer {
    fn from(args: UpdateBallsArgs) -> Self {
        Self::UpdateBalls {
            schedule: args.schedule,
        }
    }
}

impl __sdk::InModule for UpdateBallsArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateBallsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_balls`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_balls {
    /// Request that the remote module invoke the reducer `update_balls` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_balls`] callbacks.
    fn update_balls(&self, schedule: UpdateBallsSchedule) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_balls`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateBallsCallbackId`] can be passed to [`Self::remove_on_update_balls`]
    /// to cancel the callback.
    fn on_update_balls(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &UpdateBallsSchedule) + Send + 'static,
    ) -> UpdateBallsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_balls`],
    /// causing it not to run in the future.
    fn remove_on_update_balls(&self, callback: UpdateBallsCallbackId);
}

impl update_balls for super::RemoteReducers {
    fn update_balls(&self, schedule: UpdateBallsSchedule) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_balls", UpdateBallsArgs { schedule })
    }
    fn on_update_balls(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &UpdateBallsSchedule) + Send + 'static,
    ) -> UpdateBallsCallbackId {
        UpdateBallsCallbackId(self.imp.on_reducer(
            "update_balls",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateBalls { schedule },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, schedule)
            }),
        ))
    }
    fn remove_on_update_balls(&self, callback: UpdateBallsCallbackId) {
        self.imp.remove_on_reducer("update_balls", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_balls`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_balls {
    /// Set the call-reducer flags for the reducer `update_balls` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_balls(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_balls for super::SetReducerFlags {
    fn update_balls(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_balls", flags);
    }
}
