// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::food_type::Food;
use super::rgb_type::Rgb;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `foods`.
///
/// Obtain a handle from the [`FoodsTableAccess::foods`] method on [`super::RemoteTables`],
/// like `ctx.db.foods()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.foods().on_insert(...)`.
pub struct FoodsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Food>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `foods`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FoodsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FoodsTableHandle`], which mediates access to the table `foods`.
    fn foods(&self) -> FoodsTableHandle<'_>;
}

impl FoodsTableAccess for super::RemoteTables {
    fn foods(&self) -> FoodsTableHandle<'_> {
        FoodsTableHandle {
            imp: self.imp.get_table::<Food>("foods"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FoodsInsertCallbackId(__sdk::CallbackId);
pub struct FoodsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FoodsTableHandle<'ctx> {
    type Row = Food;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Food> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FoodsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FoodsInsertCallbackId {
        FoodsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FoodsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FoodsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FoodsDeleteCallbackId {
        FoodsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FoodsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Food>("foods");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct FoodsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FoodsTableHandle<'ctx> {
    type UpdateCallbackId = FoodsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FoodsUpdateCallbackId {
        FoodsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FoodsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Food>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Food>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `foods`,
/// which allows point queries on the field of the same name
/// via the [`FoodsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.foods().id().find(...)`.
pub struct FoodsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Food, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FoodsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `foods`.
    pub fn id(&self) -> FoodsIdUnique<'ctx> {
        FoodsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FoodsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Food> {
        self.imp.find(col_val)
    }
}
