// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::spawn_food_schedule_type::SpawnFoodSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `spawn_foods_schedule`.
///
/// Obtain a handle from the [`SpawnFoodsScheduleTableAccess::spawn_foods_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.spawn_foods_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.spawn_foods_schedule().on_insert(...)`.
pub struct SpawnFoodsScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpawnFoodSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `spawn_foods_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpawnFoodsScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpawnFoodsScheduleTableHandle`], which mediates access to the table `spawn_foods_schedule`.
    fn spawn_foods_schedule(&self) -> SpawnFoodsScheduleTableHandle<'_>;
}

impl SpawnFoodsScheduleTableAccess for super::RemoteTables {
    fn spawn_foods_schedule(&self) -> SpawnFoodsScheduleTableHandle<'_> {
        SpawnFoodsScheduleTableHandle {
            imp: self
                .imp
                .get_table::<SpawnFoodSchedule>("spawn_foods_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpawnFoodsScheduleInsertCallbackId(__sdk::CallbackId);
pub struct SpawnFoodsScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SpawnFoodsScheduleTableHandle<'ctx> {
    type Row = SpawnFoodSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpawnFoodSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpawnFoodsScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpawnFoodsScheduleInsertCallbackId {
        SpawnFoodsScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpawnFoodsScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpawnFoodsScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpawnFoodsScheduleDeleteCallbackId {
        SpawnFoodsScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpawnFoodsScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpawnFoodSchedule>("spawn_foods_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct SpawnFoodsScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SpawnFoodsScheduleTableHandle<'ctx> {
    type UpdateCallbackId = SpawnFoodsScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpawnFoodsScheduleUpdateCallbackId {
        SpawnFoodsScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpawnFoodsScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SpawnFoodSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpawnFoodSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `spawn_foods_schedule`,
/// which allows point queries on the field of the same name
/// via the [`SpawnFoodsScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.spawn_foods_schedule().scheduled_id().find(...)`.
pub struct SpawnFoodsScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpawnFoodSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpawnFoodsScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `spawn_foods_schedule`.
    pub fn scheduled_id(&self) -> SpawnFoodsScheduleScheduledIdUnique<'ctx> {
        SpawnFoodsScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpawnFoodsScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SpawnFoodSchedule> {
        self.imp.find(col_val)
    }
}
